version: '1'

volumes:
  microservice_db_data:


services:
  db:
    image: postgres:14.7
    container_name: db
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - microservice_db_data:/var/lib/postgresql/data
    restart: always